### PR TITLE
Fix urls returned in links header when using limit/offset

### PR DESCRIPTION
**Pull request by edudutra**
When using limit/offset, the links returned in links header are incorrect. 

The links returned are concatenating the current query options with the new ones, making it unusable. 

As an example, the following request:
`curl --request GET --url 'http://localhost:3000/api/project?limit=10'`

returns the following headers

```
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,HEAD,OPTIONS
< Access-Control-Allow-Headers: Content-Type, Authorization, Content-Length, X-Requested-With, X-HTTP-Method-Override
< X-Total-Count: 21
< Link: <http://localhost:3000/api/project?limit=10?limit=10&offset=10>; rel="next", <http://localhost:3000/api/project?limit=10?limit=10&offset=20>; rel="last"
< Content-Type: application/json; charset=utf-8
< Content-Length: 714
< ETag: W/"2ca-EuOmk/zXXNSjBkRB/JV8UuoNsAM"
< Date: Thu, 12 Nov 2020 13:55:45 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

Note the next url, for instance, where the limit is repeated:
`http://localhost:3000/api/project?limit=10?limit=10&offset=10`

The proposed correction changes the method `fullUrl`, replacing `req.originalUrl` by `req.baseUrl + req.path`, as follows:

```javascript
function fullUrl(req) {
        return req.protocol + '://' + req.get('host') + req.baseUrl + req.path
}
```

Additionally, a few tests were included to test this links

### CODE REVIEW

**Comment by pbatey** [comment]
Looks really good - thanks for catching this!

**Comment by edudutra** [comment]
Does it update automatically to npm or you have to do something?

**Comment by pbatey** [comment]
I had forgotten it was available as a node module. I'll publish an update
today.

**Comment by pbatey** [comment]
published express-mongo-rest@0.1.3

**Pull request merged**
